source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails', '4.1.8'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'thin'
gem 'tzinfo-data', platforms: [:mingw, :mswin]
gem 'haml'
gem 'devise'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'bootstrap-sass'
gem 'font-awesome-sass'
gem 'koala'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'bootstrap_form'
gem 'mysql2'
gem 'google-api-client'
gem 'pg'
gem 'rails_12factor'
gem 'bootstrap-datepicker-rails'

group :development do
  gem 'sqlite3'
  gem 'mailcatcher'
  gem 'better_errors'
  gem 'pry'
  gem 'dotenv-rails'
end
